config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'

  resources :contacts
  resources :eventpackage, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

  get 'eventpackage/index'

  get 'pricing', to: 'homes#pricing' 
  resources :ordertransactions
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Sidekiq::Web => '/sidekiq'
  resources :events  
  resources :orders 
  resources :attractions
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: 'homes#index'
  resources :homes 
  get 'directions', to: 'homes#directions'
  get 'packaging', to: 'homes#packaging'

end

app/controllers/ordertransactions_controller.rb
class OrdertransactionsController < ApplicationController
  before_action :set_ordertransaction, only: [:show, :edit, :update, :destroy]

  # GET /ordertransactions
  # GET /ordertransactions.json
  def index
    @ordertransactions = Ordertransaction.all
  end

  # GET /ordertransactions/1
  # GET /ordertransactions/1.json
  def show
  end

  # GET /ordertransactions/new
  def new
    @ordertransaction = Ordertransaction.new
  end

  # GET /ordertransactions/1/edit
  def edit
  end

  # POST /ordertransactions
  # POST /ordertransactions.json
  def create
    @ordertransaction = Ordertransaction.new(ordertransaction_params)

    respond_to do |format|
      if @ordertransaction.save
        format.html { redirect_to @ordertransaction, notice: 'Ordertransaction was successfully created.' }
        format.json { render :show, status: :created, location: @ordertransaction }
      else
        format.html { render :new }
        format.json { render json: @ordertransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordertransactions/1
  # PATCH/PUT /ordertransactions/1.json
  def update
    respond_to do |format|
      if @ordertransaction.update(ordertransaction_params)
        format.html { redirect_to @ordertransaction, notice: 'Ordertransaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordertransaction }
      else
        format.html { render :edit }
        format.json { render json: @ordertransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordertransactions/1
  # DELETE /ordertransactions/1.json
  def destroy
    @ordertransaction.destroy
    respond_to do |format|
      format.html { redirect_to ordertransactions_url, notice: 'Ordertransaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordertransaction
      @ordertransaction = Ordertransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordertransaction_params
      params[:ordertransaction]
    end
end

app/helpers/ordertransactions_helper.rb
module OrdertransactionsHelper
end

app/views/ordertransactions/_form.html.erb
<%= form_for(@ordertransaction) do |f| %>
  <% if @ordertransaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ordertransaction.errors.count, "error") %> prohibited this ordertransaction from being saved:</h2>

      <ul>
      <% @ordertransaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ordertransactions/edit.html.erb
<h1>Editing Ordertransaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @ordertransaction %> |
<%= link_to 'Back', ordertransactions_path %>

app/views/ordertransactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Ordertransactions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ordertransactions.each do |ordertransaction| %>
      <tr>
        <td><%= link_to 'Show', ordertransaction %></td>
        <td><%= link_to 'Edit', edit_ordertransaction_path(ordertransaction) %></td>
        <td><%= link_to 'Destroy', ordertransaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ordertransaction', new_ordertransaction_path %>

app/views/ordertransactions/new.html.erb
<h1>New Ordertransaction</h1>

<%= render 'form' %>

<%= link_to 'Back', ordertransactions_path %>

app/views/ordertransactions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_ordertransaction_path(@ordertransaction) %> |
<%= link_to 'Back', ordertransactions_path %>